### ISSUE TITLE
Include contact information

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-registry#2]
Should this registry contain contact info?,
Could use a format similar to that of OBO Foundry:
```
  contact:
    email: person@place.edu
    github: person
    label: This Person
```
