### ISSUE TITLE
Make clearer distinction between project-level resources and their products

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-registry#31]
This registry covers more than KGs: it includes the code used to make them, the relevant data models, mappings, and beyond.
In OBO Foundry, there's a distinction between an ontology and its products, such that a single ontology has multiple products.
e.g., ENVO has multiple products (https://obofoundry.org/ontology/envo.html) including a few different serializations and subsets.

Any KG or graph may have the following:
* The output graph, in multiple formats
* A graph dump (e.g., from Neo4J)
* A hosted endpoint for the graph or some other interface
* The code used to produce the graph
* The framework used for the graph (not a product, but a relationship)
* The data model used in the graph (not a product, but a relationship)
and beyond.

These may be better modeled in a way like how OBO Foundry does usages, so distinctions between these products and related resources can be clearly specified and presented in-line.

**Comment by justaddcoffee** [comment]
Does this distinction not already exist? (That is, how do you think this should be improved?)

For example, here's the Monarch KG, which contains a link to the repo `https://github.com/monarch-initiative/monarch-ingest` and also the `products` list (which only has one thing, but could have a link to all the various Monarch KG builds)

```
---
layout: ontology_detail
activity_status: active
id: kg-monarch
title: KG Monarch
description: Monarch Initiative Knowledge Graph
domain: health
preferredPrefix: http
contact:
  orcid: 0000-0002-6601-2165
  github: cmungall
  email: cjmungall@lbl.gov
  label: Christopher J. Mungall
homepage: https://kghub.org/kg-monarch/index.html
tracker: https://github.com/monarch-initiative/monarch-ingest/issues
repository: https://github.com/monarch-initiative/monarch-ingest
products:
- id: kg-monarch.tar.gz
  format: kgx
  title: KGX Distribution of KGM
  description: KGX Distribution of KGM
  ontology_purl: https://kg-hub.berkeleybop.io/kg-monarch/current/kg-monarch.tar.gz
uri_prefix: https://w3id.org/kg-monarch/
[snip]
```
